server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: awss3
  cloud:
    config:
      server:
        awss3:
          region: ${AWS_REGION:ap-southeast-1}
          bucket: ${AWS_CONFIG_BUCKET_NAME}

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
